from daylight.routes.register import register
from daylight.routes.complete_registration import complete_registration
from daylight.routes.login import login 
from daylight.routes.logout import logout 
from daylight.routes.profile import profile
from daylight.routes.update_profile import update_profile
from daylight.routes.upload_photo import upload_photo
from daylight.routes.delete_photo import delete_photo
from daylight.routes.suggest import suggest
from daylight.routes.like import like
from daylight.routes.matches import matches
from daylight.routes.delete_match import delete_match
from daylight.routes.rate_match import rate_match
